language: cpp
compiler:
  - gcc
  - clang
os:
  - linux

before_install:
  # GCC 4.9.x
  - if [ "$CXX" = "g++" ]; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y; fi
  - if [ "$CXX" = "g++" ]; then sudo apt-get update -qq; fi
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
  - if [ "$CXX" = "g++" ]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 50; fi
  - if [ "$CXX" = "g++" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 50; fi
  # TODO: Remove
  - nproc
  - g++ --version
  - pwd
  # Qt
  - mkdir build
  - cd build
  # qtbase
  - git clone --depth 1 --branch dev git://gitorious.org/qt/qtbase.git
  - cd qtbase
  - git checkout dev
  - ./configure -prefix ~/qt -nomake examples -nomake tests -opensource -confirm-license -release -qt-xcb -no-widgets
  - make -j$(nproc)
  - make install
  - cd ..
  - rm -rf qtbase
  # qtdeclarative
  - git clone --depth 1 --branch dev git://gitorious.org/qt/qtdeclarative.git
  - cd qtdeclarative
  - git checkout dev
  # https://codereview.qt-project.org/100434
  - git fetch --depth 1 https://codereview.qt-project.org/qt/qtdeclarative refs/changes/34/100434/2 && git checkout FETCH_HEAD
  - ~/qt/bin/qmake
  - make -j$(nproc)
  - make install
  - cd ..
  - rm -rf qtdeclarative
  - cd ..

script:
  - ~/qt/bin/qmake
  - make -j$(nproc)
