language: cpp
compiler:
  - gcc
  - clang
os:
  - linux

before_install:
  - sudo apt-get install -qq libx11-xcb-dev
  # GCC 4.9.x
  - if [ "$CXX" = "g++" ]; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y; fi
  - if [ "$CXX" = "g++" ]; then sudo apt-get update -qq; fi
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
  - if [ "$CXX" = "g++" ]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 50; fi
  - if [ "$CXX" = "g++" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 50; fi
  # Qt
  - mkdir build
  - cd build
  # qtbase
  - git clone git://gitorious.org/qt/qtbase.git
  - cd qtbase
  - git checkout dev
  - ./configure -prefix ~/qt -nomake examples -nomake tests -opensource -confirm-license -release
  - make -j$(nproc)
  - make install
  - cd ..
  # qtdeclarative
  - git clone git://gitorious.org/qt/qtdeclarative.git
  - cd qtdeclarative
  - git checkout dev
  # https://codereview.qt-project.org/100434
  - git fetch https://codereview.qt-project.org/qt/qtdeclarative refs/changes/34/100434/2 && git cherry-pick FETCH_HEAD
  - ~/qt/bin/qmake
  - make -j$(nproc)
  - make install
  - cd ..
  - cd ..



script:
  - ~/qt/bin/qmake
  - make -j$(nproc)

    